## Create Numpy array

In [17]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [28]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [42]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [45]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [49]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [53]:
b = np.zeros((3, 4))
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [57]:
b = np.full((3, 3), 5, dtype = float)
b

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [1]:
import numpy as np

a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [3]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [4]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [ ]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [5]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
b = np.full((3, 3), 5, dtype = float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [7]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
b = np.linspace(2, 10)
b
print(b[1] - b[0])
print(b[3] - b[2])

0.16326530612244916
0.16326530612244916


In [12]:
b = np.linspace(2, 10, 5, dtype = int, endpoint = False)
b

array([2, 3, 5, 6, 8])

In [10]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
b = np.eye(3, 4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
b = np.random.rand(3)
b

array([0.91222724, 0.39100305, 0.35448499])

In [15]:
b = np.random.rand(10)*10
b

array([1.53109658, 4.80079057, 6.43296798, 1.57205889, 0.32141139,
       7.81933441, 5.43656172, 1.22263946, 5.2187805 , 4.54213087])

In [16]:
b = np.random.rand(2, 3)
b

array([[0.32991299, 0.9378535 , 0.60060202],
       [0.24903288, 0.62473181, 0.98514258]])

## Mathematical Operations - 1D

In [17]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[18 19  4  1 18]
[ 6  7 11 18 15]


In [18]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [19]:
a = a + 1
a

array([19, 20,  5,  2, 19])

In [20]:
c = a + b
c

array([25, 27, 16, 20, 34])

In [ ]:
d = a - b
d


array([-5,  5,  3, 16,  8])

In [21]:
e = a * b
e

array([114, 140,  55,  36, 285])

In [22]:
f = a / b
f

array([3.16666667, 2.85714286, 0.45454545, 0.11111111, 1.26666667])

In [23]:
g = a // b
g

array([3, 2, 0, 0, 1])

In [24]:
h = a ** b
h

array([   47045881,  1280000000,    48828125,      262144, -1044074789])

In [25]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[19 20  5  2 19]
65
13.0
2
3
20
1


In [ ]:
print(a)
print(b)

[ 7 16 14 20 24]
[12 11 11  4 16]


In [ ]:
a > b

array([False,  True,  True,  True,  True], dtype=bool)

In [26]:
a < b

array([False, False,  True,  True, False])

In [27]:
a == b

array([False, False, False, False, False])

In [28]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))


[ True  True  True  True  True]
[ True  True  True  True  True]


In [29]:
a[2] = 0
print(a)
print(np.logical_not(a))

[19 20  0  2 19]
[False False  True False False]


## Boolean Indexing - 1D

In [1]:
import numpy as np

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[13 14  8  6  3 17  1 19]


In [2]:
print(b > 10)

[ True  True False False False  True False  True]


In [3]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True  True False False False  True False  True]
[13 14 17 19]


In [4]:
new_arr = b[b > 10]
new_arr

array([13, 14, 17, 19])

In [5]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([13, 14, 17])

In [6]:
print(b)
c = b
c

[13 14  8  6  3 17  1 19]


array([13, 14,  8,  6,  3, 17,  1, 19])

In [ ]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

[ 19  19  19   3 100 100   3   5]


array([100, 100, 100,   3, 100, 100,   3,   5])

In [7]:
print(b)


[13 14  8  6  3 17  1 19]


In [8]:
print(b[b == 100])

[]


In [ ]:
ind = np.where(b == 100)
ind

(array([0, 1, 2, 4, 5]),)

In [ ]:
ind = np.where(b == 100)
print(ind)
print(a[ind])

(array([0, 1, 2, 4, 5]),)
['t' 'b' 'r' 'e' 'f']


## Boolean Indexing - 2D

In [ ]:
import numpy as np
a = np.random.randint(1, 30, (5, 6))
print(a)

[[22  1 14 14  6 18]
 [19  6 22  9 21  4]
 [20 29 28 21 25  9]
 [29 28 23 27  7 17]
 [28 15 27  6 25 23]]


In [ ]:
bool_arr = a > 20
print(bool_arr)

[[ True False False False False False]
 [False False  True False  True False]
 [False  True  True  True  True False]
 [ True  True  True  True False False]
 [ True False  True False  True  True]]


In [ ]:
ans = a[bool_arr]
print(ans)

[22 22 21 29 28 21 25 29 28 23 27 28 27 25 23]


In [ ]:
b = a
print(a)

[[22  1 14 14  6 18]
 [19  6 22  9 21  4]
 [20 29 28 21 25  9]
 [29 28 23 27  7 17]
 [28 15 27  6 25 23]]


In [ ]:
b[bool_arr] = 100
print(b)

[[100   1  14  14   6  18]
 [ 19   6 100   9 100   4]
 [ 20 100 100 100 100   9]
 [100 100 100 100   7  17]
 [100  15 100   6 100 100]]


In [ ]:
c = np.random.randint(1, 10, (2, 2))
print(c)

[[4 8]
 [7 4]]


In [ ]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [ ]:
#print(c[c_bool])

In [ ]:
print(b)

[[100   1  14  14   6  18]
 [ 19   6 100   9 100   4]
 [ 20 100 100 100 100   9]
 [100 100 100 100   7  17]
 [100  15 100   6 100 100]]


In [ ]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[False False  True  True False]


In [ ]:
b[bool_arr, 3] = 99
print(b)

[[100   1  14  14   6  18]
 [ 19   6 100   9 100   4]
 [ 20 100 100  99 100   9]
 [100 100 100  99   7  17]
 [100  15 100   6 100 100]]


## Numpy Broadcasting

In [ ]:
import numpy as np

x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))
print(x)
print(y)

[[4 5 2]
 [7 8 5]
 [2 4 2]]
[[3 3 4]
 [7 1 6]
 [2 7 3]]


In [ ]:
ans = x - y
print(ans)

[[ 1  2 -2]
 [ 0  7 -1]
 [ 0 -3 -1]]


In [ ]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3))
print(x)
print(y)

[[7 7 5]
 [9 4 2]
 [5 7 5]]
[1 6 7]


In [ ]:
ans = x - y
print(ans)

[[ 6  1 -2]
 [ 8 -2 -5]
 [ 4  1 -2]]


In [ ]:
x = np.random.randint(1, 10, (3, 2))
y = np.random.randint(1, 10, (2, 3))
print(x)
print(y)

[[3 4]
 [1 3]
 [7 7]]
[[1 2 4]
 [6 4 6]]


In [ ]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[1 6]
 [2 4]
 [4 6]]
[[ 2 -2]
 [-1 -1]
 [ 3  1]]
